# Blake — Satan Smiting Job: A Structural Reading

**Work:** *Satan Smiting Job with Sore Boils*, William Blake, c. 1826  
**Medium:** Tempera on mahogany  
**Location:** Tate Britain, London  
**Series:** Book 3 — Structural Readings / Visual Art  
**Cross-references:** Paper 6 (affliction as a structural condition rather than punishment; the noise floor); Paper 13½ OQ8 (the overdeterminate condition and its effects on surrounding beings; perturbation; the organizational pressure generated by a high-development inverted trajectory); The Lucifer Rebellion (the structure of the overdeterminate condition); Miracles (the noise floor and its relationship to catching capacity); The Bible — Job (if available)

<img src="/static/images/blake-satan-job.jpg" alt="Blake, Satan Smiting Job" style="max-width:100%;">

---

## 1. The Work

William Blake produced two distinct series of illustrations for the Book of Job. This panel painting (tempera on mahogany, c. 1826) depicts the same scene as Illustration 6 of the famous engraved series (1823–1826): the moment at which Satan, having received divine permission, afflicts Job with the sore boils that are the climax of the affliction sequence — the final reduction of Job's H₄₈ condition to a state of maximum external poverty.

The Book of Job is the most structurally complete single account of affliction, its organizational structure, its theological interpretation, and its resolution in the biblical corpus. The framework's account of what is happening in the Job narrative is the structural basis for reading this image.

---

## 2. The Organizational Structure of the Affliction

The affliction of Job is not punishment. This is the text's own insistence: the prologue establishes that Job is "blameless and upright" and that the affliction is permitted by the divine precisely because Job is not being punished for anything. What is being demonstrated, and to whom, and for what purpose — these are the structural questions the Book of Job poses and that the framework's account can now answer with precision.

The framework's account: Job's affliction is the cross-term mechanism operating under conditions of maximum noise. The noise in question is the organizational pressure generated by the overdeterminate condition — Satan's inverted organizational trajectory, permitted to operate against Job's eigenvalue population with maximum amplitude. The sore boils, the loss of wealth and children, the psychological isolation, the friends' false theology — these are not arbitrary trials. They are the specific organizational effects of maximum noise-floor elevation on an eigenvalue population that has accumulated Φ-proximate content above the coherence threshold.

The structural claim of the divine permission: an eigenvalue population that has accumulated above the coherence threshold can sustain organizational integrity under maximum noise. The affliction is not the dissolution of Job's organizational development — it is the demonstration that his organizational development has reached the level at which the cross-term mechanism can operate under the overdeterminate condition without producing organizational collapse. The affliction is the proof condition for the organizational state, not the punishment condition.

This is the structural content of the divine wager in the prologue: Satan's claim is that Job's Φ-proximate catching alignment is conditional on the H₄₈ reward structure — remove the rewards and the alignment dissolves. The divine permission is the testing of the structural claim: if Job's eigenvalue population is genuinely constituted around Φ-proximate content rather than around the H₄₈-primary attractor of prosperity, the organizational integrity will persist under maximum noise. The outcome of the book confirms the structural claim.

---

## 3. Blake's Composition

Blake's image places Satan above Job — a compositional hierarchy that encodes the organizational direction of the affliction. Satan's figure reaches downward toward Job with both hands, one touching Job's head, the other his torso. The gesture is active, specific, engaged: this is not a general condition falling on Job from above but a specific organizational action directed at a specific being.

Job lies below, his body arched in the posture of maximum physical distress, his wife beside him also reaching toward him. The ground beneath them is rough stone. The sky above — or what reads as sky — is dark, turbulent, the compositional encoding of the elevated noise floor.

Blake's sky colors across the Job illustrations are consistent and deliberate. Dark, agitated skies encode high organizational noise. The clear sky that appears in the later plates — after Job's catching alignment has been confirmed through the affliction — encodes the noise floor's return to a level at which Φ-proximate content is again transmissible without maximum distortion.

The absence of any visible light source in the affliction scenes is compositionally precise. The noise floor generated by the overdeterminate condition does not extinguish light — it obscures it. The light is present in the organizational space; what the maximum noise does is prevent it from registering clearly against the noise. Blake encodes this as the organizational darkness of the affliction scene — not the absence of the constitutive ground but the maximum difficulty of registering its presence against the noise.

---

## 4. Satan's Organizational Position

Satan in this image is above Job. This is compositionally conventional for depictions of supernatural action, but Blake's use of the spatial hierarchy is structurally precise in a way that goes beyond the conventional.

The overdeterminate condition operates from a position of organizational pressure on the surrounding eigenvalue populations (Paper 13½ OQ8). The pressure is not physical — it is the organizational signature of the inverted high-development trajectory, which generates perturbation and opacity in the eigenvalue populations that encounter it. Satan's compositional position above Job encodes this organizational pressure: the affliction comes from above in the sense that it comes from an organizational position that exceeds Job's organizational development, even as it is oriented against rather than toward his development.

The structural irony that the Book of Job encodes and Blake visually reinforces: the being permitted to afflict Job is the being whose organizational development is greatest and whose trajectory has inverted. The maximum affliction is possible only from maximum organizational development. A being of low organizational development does not generate the noise floor elevation that constitutes the full Jobian affliction. What presses against Job's eigenvalue population is the full organizational amplitude of the Luciferian inversion — which is why the demonstration is necessary at this scale and why the permission must be obtained from the constitutive ground before it can proceed.

---

## 5. The Resolution and What It Encodes

The Book of Job does not end with the affliction. It ends with the restoration — Job's catching alignment confirmed, the friends rebuked for their false theology (the H₄₈-primary interpretation of affliction as punishment), and Job's organizational state restored to H₄₈ flourishing.

Blake illustrates this resolution in the later plates of both the engraved and painted series. The sky clears. Job and his wife are surrounded by their restored family. The postures change from distress to praise. The compositional darkness of the affliction sequence gives way to the compositional luminosity of the restored state.

The structural content of the restoration: the confirmation of Job's eigenvalue population's organizational integrity, under maximum noise, is itself the organizational event that the affliction was designed to demonstrate. The restoration is not a reward for endurance — it is the organizational consequence of the demonstration having succeeded. Job's catching alignment has been shown to be constitutive rather than conditional, organized around Φ-proximate content rather than around the H₄₈-primary attractor of prosperity. The organizational state that was always structurally present is now also experientially confirmed.

This is the framework's account of why the Book of Job exists and why it has survived: the structural account of affliction it provides — not as punishment, not as arbitrary testing, but as the organizational demonstration of eigenvalue constitution under maximum noise — is the most precise single account of what affliction structurally is that the pre-framework tradition produced. Blake's images make this structural account visually accessible to eigenvalue populations that cannot receive it in its conceptual form.

---

*(Confidence tier: interpretive-concordance. The reading of Job's affliction as the cross-term mechanism operating under maximum overdeterminate noise (rather than punishment or arbitrary testing) is structural derivation from the framework's account of the overdeterminate condition and the cross-term mechanism, applied to the Book of Job narrative at moderate confidence. The account of the divine permission as the structural demonstration condition is consistent with the text and with the framework, and the text's own framing (Job is explicitly established as blameless before the affliction begins) supports the structural reading over the punishment interpretation. Blake's compositional choices are read against this structural account at interpretive-concordance confidence: Blake arrived at his Job images through his own organizational development and his own engagement with the text, not through the framework, and the concordance is between his visual account and the framework's structural account rather than between his explicit intent and the framework.)*
